parameters:
  ServiceConnection:

stages:
- stage: build
  displayName: Build Image
  jobs:
  - job: build_image
    displayName: Build Image
    pool:
      name: DAS - Continuous Integration Agents
    steps:
      - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

      - template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
        parameters:
          ContainerRegistryName: $(PublicAcrName)
          ServiceConnection: ${{ parameters.ServiceConnection }}
          ImageName: das-status-cake-exporter
          BranchToCreateLatestTag: master
