trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - exporter/*
      - pipeline-templates/*
      - azure-pipelines.yml
      - requirements.txt
      - Dockerfile

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.61
    endpoint: SFA

variables:
- group: Release Management Resources
- group: Statuscake API
- name: AKSNamespace
  value: monitoring
- name: KubectlVersion
  value: 1.18.8

stages:
  - template: /pipeline-templates/stage/build.yml
    parameters:
      ServiceConnection: SFA-DIG-Prod-ARM

  - stage: Deploy_Dev
    variables:
    - group: Dev Management Resources
    jobs:
    - template: /pipeline-templates/job/deploy.yml
      parameters:
        AKSClusterName: $(AKSSharedClusterName)
        AKSResourceGroupName: $(AKSResourceGroupName)
        AKSNamespace: $(AKSNamespace)
        AzureServiceConnection: SFA-DAS-DevTest-ARM
        Environment: DEV
        KubectlVersion: $(KubectlVersion)
        StatuscakeUsername: $(StatuscakeUsername)
        StatuscakeExporterAPIKey: $(StatuscakeExporterAPIKey)

  - stage: Deploy_Prod
    dependsOn: Deploy_Dev
    variables:
    - group: Prod Management Resources
    jobs:
    - template: /pipeline-templates/job/deploy.yml
      parameters:
        AKSClusterName: $(AKSSharedClusterName)
        AKSResourceGroupName: $(AKSResourceGroupName)
        AKSNamespace: $(AKSNamespace)
        AzureServiceConnection: SFA-DIG-Prod-ARM
        Environment: PROD
        KubectlVersion: $(KubectlVersion)
        StatuscakeUsername: $(StatuscakeUsername)
        StatuscakeExporterAPIKey: $(StatuscakeExporterAPIKey)