trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - exporter/*
      - pipeline-templates/*
      - azure-pipelines.yml
      - requirements.txt
      - Dockerfile

pr: none

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.2.21
    endpoint: SFA

variables:
- name: KubectlVersion
  value: 1.18.8

stages:
  - template: /pipeline-templates/stage/build.yml
  - stage: DeployTo_DEV
    displayName: DeployTo_DEV
    variables:
    - group: Dev Management Resources
    jobs:
    - template: /pipeline-templates/job/deploy.yml
      parameters:
        AksClusterName: $(AKSSharedClusterName)
        AksResourceGroupName: $(AKSResourceGroupName)
        AzureServiceConnection: SFA-DAS-DevTest-ARM
        Environment: DEV
        KubectlVersion: $(KubectlVersion)