trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - exporter/*
      - pipeline-templates/*
      - azure-pipelines.yml
      - requirements.txt
      - Dockerfile

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.1.0
    endpoint: SkillsFundingAgency

variables:
- group: Release Management Resources
- group: Statuscake API
- name: AKSNamespace
  value: monitoring
- name: KubectlVersion
  value: 1.23.8

stages:
  - template: /pipeline-templates/stage/build.yml
    parameters:
      ServiceConnection: SFA-DIG-Prod-ARM

  - stage: Deploy_PreProd
    variables:
    - group: PreProd Management Resources
    jobs:
    - template: /pipeline-templates/job/deploy.yml
      parameters:
        AKSClusterName: $(AKSSharedClusterName)
        AKSResourceGroupName: $(AKSResourceGroupName)
        AKSNamespace: $(AKSNamespace)
        AzureServiceConnection: SFA-DIG-PreProd-ARM
        Environment: PREPROD
        KubectlVersion: $(KubectlVersion)
        StatuscakeUsername: $(StatuscakeUsername)
        StatuscakeExporterAPIKey: $(StatuscakeExporterAPIKey)

  - stage: Deploy_Prod
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'Manual')))
    dependsOn: Deploy_PreProd
    variables:
    - group: Prod Management Resources
    jobs:
    - template: /pipeline-templates/job/deploy.yml
      parameters:
        AKSClusterName: $(AKSSharedClusterName)
        AKSResourceGroupName: $(AKSResourceGroupName)
        AKSNamespace: $(AKSNamespace)
        AzureServiceConnection: SFA-DIG-Prod-ARM
        Environment: PROD
        KubectlVersion: $(KubectlVersion)
        StatuscakeUsername: $(StatuscakeUsername)
        StatuscakeExporterAPIKey: $(StatuscakeExporterAPIKey)
