parameters:
  AksClusterName:
  AksResourceGroupName:
  AzureServiceConnection:
  Environment:
  KubectlVersion:

jobs:
- deployment: DeployTo_${{ parameters.Environment }}
  environment: ${{ parameters.Environment }}
  pool:
    name: 'DAS - Continuous Integration'
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          path: 'das-status-cake-exporter/'
        - task: replacetokens@3
          displayName: 'Replace tokens in $(Pipeline.Workspace)/das-status-cake-exporter/manifests'
          inputs:
            rootDirectory: '$(Pipeline.Workspace)/das-status-cake-exporter/manifests'
            targetFiles: '*.yml'
            encoding: 'auto'
            writeBOM: true
            actionOnMissing: 'fail'
            keepToken: false
            tokenPrefix: '__'
            tokenSuffix: '__'
            verbosity: detailed
        - task: KubectlInstaller@0
          displayName: 'Install Kubectl 1.18.8'
          inputs:
            kubectlVersion: 1.18.8
        - task: Kubernetes@1
          displayName: 'Create Deployment'
          inputs:
            azureSubscriptionEndpoint: ${{ parameters.AzureServiceConnection }}
            azureResourceGroup: ${{ parameters.AksResourceGroupName }}
            connectionType: Azure Resource Manager
            kubernetesCluster: ${{ parameters.AksClusterName }}
            namespace: monitoring
            useConfigurationFile: true
            configuration: $(Pipeline.Workspace)/das-status-cake-exporter/manifests/config-secrets.yml
            secretType: generic
            useClusterAdmin: true
        - task: Kubernetes@1
          displayName: 'Create Deployment'
          inputs:
            azureSubscriptionEndpoint: ${{ parameters.AzureServiceConnection }}
            azureResourceGroup: ${{ parameters.AksResourceGroupName }}
            connectionType: Azure Resource Manager
            kubernetesCluster: ${{ parameters.AksClusterName }}
            namespace: monitoring
            command: apply
            useConfigurationFile: true
            configuration: $(Pipeline.Workspace)/das-status-cake-exporter/manifests/deployment.yml
            useClusterAdmin: true