parameters:
  AksClusterName:
  AksResourceGroupName:
  AzureServiceConnection:
  Environment:
  KubectlVersion:

jobs:
- deployment: DeployTo_${{ parameters.Environment }}
  environment: ${{ parameters.Environment }}
  pool:
    name: 'DAS - Continuous Integration'
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          path: 'das-status-cake-exporter/'
        - task: replacetokens@3
          displayName: 'Replace tokens in $(Pipeline.Workspace)/das-status-cake-exporter/manifests'
          inputs:
            rootDirectory: '$(Pipeline.Workspace)/das-status-cake-exporter/manifests'
            targetFiles: '*.yml'
            encoding: 'auto'
            writeBOM: true
            actionOnMissing: 'fail'
            keepToken: false
            tokenPrefix: '__'
            tokenSuffix: '__'
        - template: azure-pipelines-templates/deploy/step/kubernetes-apply-manifest.yml@das-platform-building-blocks
          parameters:
            AksClusterName: ${{ parameters.AksClusterName }}
            AksResourceGroupName: ${{ parameters.AksResourceGroupName }}
            AzureServiceConnection: ${{ parameters.AzureServiceConnection }}
            KubectlVersion: ${{ parameters.KubectlVersion }}
            ManifestFile: $(Pipeline.Workspace)/das-status-cake-exporter/manifests/deployment.yml
            Namespace: monitoring
