parameters:
  AKSClusterName:
  AKSResourceGroupName:
  AKSNamepsace:
  AzureServiceConnection:
  Environment:
  KubectlVersion:
  StatusCakeUsername:
  StatuscakeExporterAPIKey:

jobs:
- deployment: DeployTo_${{ parameters.Environment }}
  environment: ${{ parameters.Environment }}
  pool:
    name: 'DAS - Continuous Integration'
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          path: 'das-status-cake-exporter/'
        - task: Kubernetes@1
          displayName: kubectl create status-cake-api-token secret
          inputs:
            connectionType: Azure Resource Manager
            azureSubscriptionEndpoint: ${{ parameters.AzureServiceConnection }}
            azureResourceGroup: ${{ parameters.AKSResourceGroupName }}
            kubernetesCluster: ${{ parameters.AKSClusterName }}
            useClusterAdmin: true
            namespace: ${{ parameters.AKSNamespace }}
            secretType: generic
            secretArguments: --from-literal=USERNAME=${{ parameters.StatuscakeUsername }} --from-literal=API_KEY=${{ parameters.StatuscakeExporterAPIKey }}
            secretName: status-cake-api-token
        - task: replacetokens@3
          displayName: 'Replace tokens in $(Pipeline.Workspace)/das-status-cake-exporter/manifests'
          inputs:
            rootDirectory: '$(Pipeline.Workspace)/das-status-cake-exporter/manifests'
            targetFiles: '*.yml'
            encoding: 'auto'
            writeBOM: true
            actionOnMissing: 'fail'
            keepToken: false
            tokenPrefix: '__'
            tokenSuffix: '__'
        - template: azure-pipelines-templates/deploy/step/kubernetes-apply-manifest.yml@das-platform-building-blocks
          parameters:
            AksClusterName: ${{ parameters.AKSClusterName }}
            AksResourceGroupName: ${{ parameters.AKSResourceGroupName }}
            AzureServiceConnection: ${{ parameters.AzureServiceConnection }}
            KubectlVersion: ${{ parameters.KubectlVersion }}
            ManifestFile: $(Pipeline.Workspace)/das-status-cake-exporter/manifests/deployment.yml
            Namespace: ${{ parameters.AKSNamespace }}
