apiVersion: v1
kind: Service
metadata:
  name: prometheus-status-cake-exporter
  labels:
    app: prometheus-status-cake-exporter
spec:
  ports:
  - name: metrics
    port: 8000
    protocol: TCP
  selector:
    app: prometheus-status-cake-exporter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-status-cake-exporter
  labels:
    app: prometheus-status-cake-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-status-cake-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prometheus-status-cake-exporter
    spec:
      nodeSelector:
        agentpool: monitoring01
      containers:
      - name: status-cake-exporter
        image: apprenticeshipsdevops/das-status-cake-exporter:__Build.BuildNumber__
        ports:
        - containerPort: 8000
        env:
        - name: USE_V1_UPTIME_ENDPOINTS
          value: __StatuscakeUseV1UptimeEndpoints__
        - name: USE_V1_MAINTENANCE_WINDOWS_ENDPOINTS
          value: __StatuscakeUseV1MaintenanceWindowsEndpoints__
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: status-cake-api-token
              key: USERNAME
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: status-cake-api-token
              key: API_KEY
        - name: TAGS
          value: "DAS"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: status-cake-exporter
  namespace: monitoring
  labels:
    app: prometheus
spec:
  jobLabel: status-cake-exporter
  selector:
    matchLabels:
      app: prometheus-status-cake-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: metrics
    interval: 1m
    scrapeTimeout: 1m
    path: /